version: "3.3"

services:
    app:
        build:
            dockerfile: Dockerfile
        ports:
            - "9001:80"
            - "3001:3001"
        platform: linux/amd64
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - ./:/var/www/html:rw
        networks:
            - projectManagementNetwork

    db:
        image: 'mysql/mysql-server:8.0'
        restart: unless-stopped
        ports:
            - '3398:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'helper'
            MYSQL_USER: 'helper'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'projectManagementMysqlData:/var/lib/mysql'
        networks:
            - projectManagementNetwork
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-ppassword" ]
            retries: 3
            timeout: 5s
        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
volumes:
    projectManagementMysqlData:
        driver: local

networks:
    projectManagementNetwork:
        driver: bridge
